eshop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('accounts/', include('apps.accounts.urls')),    
    path('seller_accounts/', include('apps.seller_accounts.urls')),
    path('cart/', include('apps.cart.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.main.views.error_404_view'

apps/cart/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from apps.accounts.models import *
from apps.seller_accounts.models import *
# Create your models here.

# class Category(models.Model):
#     title = models.CharField(max_length=200)
#     slug = models.SlugField(unique=True)

#     def __str__(self):
#         return self.title

class Product(models.Model):
    title = models.CharField(max_length=200)
    gender_cat = models.CharField(max_length=50,null=True)
    sub_cat = models.CharField(max_length=50,null=True)
    articel_type = models.CharField(max_length=50,null=True)
    market_price = models.PositiveIntegerField()
    discount_price = models.PositiveIntegerField(default=0)
    description = models.TextField()
    seller = models.ForeignKey(CompanyDetails, on_delete=models.SET_NULL,null=True)
    brand = models.CharField(max_length=200,null=True)
    color = models.CharField(max_length=200,null=True)
    size = models.CharField(max_length=5,default="S")
    material = models.CharField(max_length=200,null=True)
    completelook = models.TextField(null=True)
    
    def __str__(self):
        return self.title

class ProductImagesFiles(models.Model):
    product = models.ForeignKey(Product,on_delete=CASCADE)
    image_file = models.ImageField(upload_to="products",blank=True)

class ProductImagesURL(models.Model):
    product = models.ForeignKey(Product,on_delete=CASCADE)
    image_url = models.URLField(max_length=500,blank=True)
    

class Cart (models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "  CartProduct: " + str(self.id)

ORDER_STATUS = (
    ("Order Placed","Order Placed"),
    ("Order Processing","Order Processing"),
    ("Order Completed","Order Completed"),
    ("Order Canceled","Order Canceled"),
    ("On the way","On the way")
)
    
class Sales(models.Model):
        company = models.ForeignKey(CompanyDetails, on_delete=models.CASCADE)
        product = models.ForeignKey(Product, on_delete=models.CASCADE)
        rate = models.PositiveIntegerField(default=0)
        quantity = models.PositiveIntegerField(default=0)
        subtotal = models.PositiveIntegerField(default=0)

        def __str__(self):
            return "Product: " + str(self.product) + " Sales: " + str(self.subtotal)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by =models.CharField(max_length=200)
    shipping_address =models.CharField(max_length=200)
    
    mob_no = models.CharField(max_length=12, null=True, blank=True)
    email = models.EmailField(blank=True)
    subtotal =models.PositiveIntegerField(null=True, blank=True)
    discount =models.PositiveIntegerField(null=True, blank=True)
    total =models.PositiveIntegerField(null=True, blank=True)
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: " + str(self.id)
    
    

templates/ajax/product-list.html
{% for product in product_list %}
            <div class="col-md-4 col-sm-6 px-2 mb-4">
              <div class="card product-card">
                <button class="btn-wishlist btn-sm" type="button" data-bs-toggle="tooltip" data-bs-placement="left" title="Add to wishlist"><i class="ci-heart"></i></button><a class="card-img-top d-block overflow-hidden" href="{% url 'apps.main:single_product' product.id  %}">
                <div style="height:300px">
                  {% if product.productimagesfiles_set.all %}
                      {% for product_img in product.productimagesfiles_set.all|slice:":1" %}
                        <img src="{{product_img.image_file.url}}" alt="Product">
                      {%endfor%}
                    {%else%}
                      {% for product_img in product.productimagesurl_set.all|slice:":1" %}
                        <img src="{{product_img.image_url}}" alt="Product">
                      {%endfor%}
                    {% endif %}
                </div>
                </a>
                <div class="card-body py-2"><a class="product-meta d-block fs-xs pb-1" href="#">{{product.category}}</a>
                  <h3 class="product-title fs-sm"><a href="{% url 'apps.main:single_product' product.id  %}">{{product.title}}</a></h3>
                  <div class="d-flex justify-content-between">
                    <div class="product-price"><span class="text-accent">Tsh {{product.market_price}}/=</span></div>
                    <div class="star-rating"><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star"></i>
                    </div>
                  </div>
                </div>
                <div class="card-body card-body-hidden">
                    
                    {% if user.is_staff %}
                    <button class="btn btn-primary btn-sm d-block w-100 mb-2 disabled" type="button"><i class="ci-cart fs-sm me-1"></i>Add to Cart</button>
                    {% else %}
                    <a href="{% url 'apps.cart:addtocart' product.id %}">
                    <button class="btn btn-primary btn-sm d-block w-100 mb-2" type="button"><i class="ci-cart fs-sm me-1"></i>Add to Cart</button>
                    </a>
                    {% endif %}
                    
                  </div>
                </div>
              <hr class="d-sm-none">
            </div>
    {% endfor %}
     

templates/ajax/product-list_search_result.html
{% for product in search_result %}
          <div class="card product-card product-list">
            <button class="btn-wishlist btn-sm" type="button" data-bs-toggle="tooltip" data-bs-placement="left" title="Add to wishlist"><i class="ci-heart"></i></button>
            <div class="d-sm-flex align-items-center"><a class="product-list-thumb" href="{% url 'apps.main:single_product' product.id %}">
            {% if product.productimagesfiles_set.all %}
              {% for product_img in product.productimagesfiles_set.all|slice:":1" %}
                <img src="{{product_img.image_file.url}}" alt="Product">
              {%endfor%}
            {%else%}
              {% for product_img in product.productimagesurl_set.all|slice:":1" %}
                <img src="{{product_img.image_url}}" alt="Product">
              {% endfor %}
            {% endif %}
            
            </a>
              <div class="card-body py-2"><a class="product-meta d-block fs-xs pb-1" href="#">{{product.category}}</a>
                <h3 class="product-title fs-base"><a href="{% url 'apps.main:single_product' product.id %}">{{product.title}}</a></h3>
                <div class="d-flex justify-content-between">
                  <div class="product-price"><span class="text-accent">Tsh {{product.market_price}}/=</span></div>
                  <div class="star-rating"><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star-filled active"></i><i class="star-rating-icon ci-star"></i>
                  </div>
                </div>
                <div class="card-body card-body-hidden">
                  <div class="pb-2">
                    <div class="form-check form-option form-check-inline mb-2">
                      <input class="form-check-input" type="radio" name="size1" id="s-75">
                      <label class="form-option-label" for="s-75">7.5</label>
                    </div>
                    <div class="form-check form-option form-check-inline mb-2">
                      <input class="form-check-input" type="radio" name="size1" id="s-80" checked>
                      <label class="form-option-label" for="s-80">8</label>
                    </div>
                    <div class="form-check form-option form-check-inline mb-2">
                      <input class="form-check-input" type="radio" name="size1" id="s-85">
                      <label class="form-option-label" for="s-85">8.5</label>
                    </div>
                    <div class="form-check form-option form-check-inline mb-2">
                      <input class="form-check-input" type="radio" name="size1" id="s-90">
                      <label class="form-option-label" for="s-90">9</label>
                    </div>
                  </div>
                  <a href="{% url 'apps.cart:addtocart' product.id %}">
                  <button class="btn btn-primary btn-sm mb-2" type="button"><i class="ci-cart fs-sm me-1"></i>Add to Cart</button></a>
                  <div class="text-start"><a class="nav-link-style fs-ms" href="#quick-view" data-bs-toggle="modal"><i class="ci-eye align-middle me-1"></i>Quick view</a></div>
                </div>
              </div>
            </div>
          </div>
          <div class="border-top pt-3 mt-3"></div>
        {% endfor %}